### ISSUE TITLE
[tracking] Releasing procedures

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1016]
This is a tracking issue for various ways to release Acter in the wild and making sure people stay up to date with the latest development. We are using two different github workflows to directly ship the app: Nightly and Publish -- the former being run every day (if there have been changes merged), the latter every other week manually. Neither is complete and this tracking issue keeps a list of the things we want to improve upon them.

**Infrastructure**:
 - [ ] Automatic upgrades depending on the channel in use 
       (maybe use [upgrade](https://pub.dev/packages/upgrade) or [upgrader](https://pub.dev/packages/upgrader) package)
 - [ ] publish isn't happening if any of the matrix-jobs is cancelled ...
 
**Nightly**:
 - [ ] iOS and MacOS build are broken since [2023-09-28](https://github.com/acterglobal/a3/releases/tag/nightly-2023-09-28)
 - [ ] Windows nightly builds should use msix

**Publish**:
 - Windows:
     - [ ] automatic shipping to MS Store doesn't work yet
     - [ ] build at Github Release is unsigned
 - MacOS:
     - [ ] upload to AppStore is rejected because of weird signature issue
 - Linux:
     - [ ] Publish to SnapCraft
     - [ ] Publish as deb
     - [ ] Publish as rpm 
 - Android:
     - [ ] submit target specific Apk to Github Release
     - [ ] publish to fdroid 
 - iOS:
     - [ ] automatic release creation and submission for review?!?
 - [ ] Publish Github Release
