### ISSUE TITLE
Rework Pins tracking

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1273]
From https://github.com/acterglobal/UX/issues/138

- [x] show pin content in overview list if it just a small text
- [x] clean up spacing, padding and designs
- [x] include pins in quick-jump search
- [x] add attachments
- [x] show main attachment in overview
- [x] add comments
- [x] add likes
- [ ] #1621
- [x] define new creation and editing methods
- [x] #1274

**Comment by gnunicorn** [comment]
closing with only one item open.
