### ISSUE TITLE
[tracking] localization and i18n

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1299]
We want to have our App available in the users language and local settings (e.g. way to write dates, numbers, etc).

- [x] #1334
- [x] #1517
- [x] research a way to include i18n translations for strings from rust
- [x] left-to-right support
- [ ] extract rust local error-string into a local Error-Type instead
- [x] crowdsource translation helper (e.g. weblate.org, transifex)
- [x] automatized string extraction and  file upload to crowdsourcing platform
- [x] automatize crowdsource file integration on builds.

**Comment by gnunicorn** [comment]
considered done for now.
