### ISSUE TITLE
Barriers for user adoption (Tracking)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1524]
Bugs
- [x] Os Error 1 #1422 
- [x] Failed to decrypt (Bjarke+Djangz) (issue 145 in meta)
- [x] #1544 
- [x] #1362 
- [x] Not loading chats, #1343
- [ ] Display correct chat order #1332 #1034 
- [x] Generel Loading issues 
   - [x] #1142
   - [x] #1086
   - [x] #1107 
__________________________

Onboarding
- [x] explanation and/or where to find invite code #1444 
- [x] Password recovery (through email) : #877 #920 #1446 #1445 
- [x] guidance regarding encryption ("failed to decrypt") https://github.com/acterglobal/a3-meta/issues/145 https://github.com/acterglobal/a3-meta/issues/146
- [x] #1633
- [x] support with verification #1008 
- [x] Product onboarding: Navigating Acter #1443 #1442
- [x] in-app signs for unread messages #845 
- [x] #1540 
- [x] how to invite/organize others/own community (not on matrix) 👉 next steps for task force; maybe #864 
__________________________

Notifications:
- [x] See all unread chats Filter; needs #812 

Navigation:
- [x] Visibility and accessibility settings + indicators #1379 
- [x] Space avatar indicators for chats and spaces. #1122 
- [x] #1689

Chat
- [x] Highlight text / copy text #1074 
- [x] Download image automatically  #1476
- [x] Better view of images and video in chat + no need to show image name/title when clicking on images #1250 , #1416
- [x] finish chat creation flow (add/invite all people from a space(s) #796 
- [x] #1664

Events:
- [x] #1525
__________________________

Future Registration
- [ ] Enable people to save session keys

integrations
- [ ]

**Comment by gnunicorn** [comment]
@emilvincentz I linked up every issue listed and gave them the appropriate `onboarding`-quest association so we have them closer to heart. The ones left open right now I need more input from what this is about or what is meant with that. You can either tell me directly or create an issue and link it (that can easily be done by hovering over the list item in the full issue view and click the target-icon on the left, then github creates that as an issue and links it) and describe the details there.

**Comment by gnunicorn** [comment]
I think this has run its course, closing it for now.
