### ISSUE TITLE
[tracking] General debt tech clean ups

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1567]
Minor fixes and refactors, mostly of old code that needs to be converted into the new version of it:

- [ ] Replace `customSnackBar` with `EasyLoading`
- [ ] replace `ref.invalid` with proper notifiers that listen to SDK events

and Improved Logging support
- [ ] add `_log.error` for all `error:()`-loaders (including stack)
- [ ] add `_log.error` for all `try-catch-cases` (including stack)
- [ ] add `_log.error` for all `EasyLoading.showError`
