### ISSUE TITLE
Ready state Fixes (Tracking)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1787]
Blockers
- [x] Os Error: too many files open + Error sending Request [#1788](https://github.com/acterglobal/a3/issues/1788)
- [x] crashed on last session. [#275](https://github.com/acterglobal/a3-meta/issues/275)
- [x] MacOS opens with black screen [#1728](https://github.com/acterglobal/a3/issues/1728)
- [x] [Cant delete in chat on desktop ](https://github.com/acterglobal/a3-meta/issues/246)

Higher priority
- [x] [new message in chat does not show up on the chat list](https://github.com/acterglobal/a3-meta/issues/285)
- [x] [error loading image in chat](https://github.com/acterglobal/a3-meta/issues/261)
- [x] video displayd in small format[#249](https://github.com/acterglobal/a3-meta/issues/249)
- [x] Can not view files/pdf's in acter chat [#1663](https://github.com/acterglobal/a3/issues/1663)
- [x] keyboard doesn’t any longer close on scroll up [#213](https://github.com/acterglobal/a3-meta/issues/213)
- [x] Keyboard cover when uploading files and also after posting files [#1790](https://github.com/acterglobal/a3/issues/1790)
- [x] https://github.com/acterglobal/a3-meta/issues/253
- [x] Doesnt make a space when making a paragraph in chat [#1855](https://github.com/acterglobal/a3/issues/1855)
- [ ] when click "share in chat" room id is not functional [#1740](https://github.com/acterglobal/a3/issues/1740)
- [x] https://github.com/acterglobal/a3-meta/issues/255
- [x] https://github.com/acterglobal/a3-meta/issues/254
- [x] [can not delete event due to error message #253](https://github.com/acterglobal/a3-meta/issues/253)
- [x] https://github.com/acterglobal/a3-meta/issues/252
- [ ] https://github.com/acterglobal/a3-meta/issues/251
- [ ] no closing button on update event widget modal https://github.com/acterglobal/a3-meta/issues/250
- [x] [Event description field does not work when entering edit mode](https://github.com/acterglobal/a3-meta/issues/263)
- [x] not able to download attachments [#1711](https://github.com/acterglobal/a3/issues/1711)
- [ ] not able to preview push notification content on ios [#1615](https://github.com/acterglobal/a3/issues/1615)
- [x] Events does not update after editing [#1816](https://github.com/acterglobal/a3/issues/1816)
- [x] Linking a space, shows up as a recommended space [#1863](https://github.com/acterglobal/a3/issues/1863)

Lower priority
- [x] Grey screen upon Update create https://github.com/acterglobal/a3-meta/issues/247
- [x] When you delete a pin within a space, it goes to your home section afterwards. It should stay on the space. [#1815](https://github.com/acterglobal/a3/issues/1815)
- [x] [ ] Blob from text editor shows [#1679](https://github.com/acterglobal/a3/issues/1679)
- [x] https://github.com/acterglobal/a3-meta/issues/258
- [x] auto generated DM via super invites, show up as a room and not DM avatar [#1530](https://github.com/acterglobal/a3/issues/1530)
- [x] Emoji Reaction to messages UI is only showing 4 emojiis at a time
[#1793](https://github.com/acterglobal/a3/issues/1793)
- [x] Leaving space, does still show alert box [#1807](https://github.com/acterglobal/a3/issues/1807)
- [x] Jumps over the the inital letter in event description field [#1818](https://github.com/acterglobal/a3/issues/1818)
- [x] when scrolling up on side modal, it stalls
[#1752](https://github.com/acterglobal/a3/issues/1752)

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Most of the issues in this tracking are fixed, so can we close this?
