### ISSUE TITLE
Dragonfly Tracking

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1835]
- [x] #1841
       - Delete Task List & Task Item
       - Report Task List & Task Item
       - Inline due date
       - General UI-UX improvements

- [x] #1845
       - Tap on any avatar to view it in full screen
       - Edit avatar from full screen based on the permission

- [x] #1838
       - Tap on any title to change it based on the permission
       - Three dot menu option will also have Edit Title menu based on the permission

- [x] #1842
       - Tap on any description to change it based on the permission
       - Three dot menu option will also have Edit Description menu based on the permission

- [x] #1843

- [x] #1844
       - Change main colour scheme from blue theme to dark & grey theme

- [x] #1879
       - Header area with User greetings, Search, Quick actions of Pins, Events, Task and Announcements
       - My Tasks List
       - My Events List
       - My Spaces List

- [x] #1884
       - Header area with collapsing view as per reference app (Zomato Restaurant Detail Page)
       - Space menus with single page scrolling behaviour
       - Quick action button at the bottom side (Add Pin, Add Task, Add Event, Add Announcements)

- [x] #1925
       - Generalised full screen view for Pins, Events, and Tasks which can be used for All Items view and Space Items view
       - Search option

- [x] #2163
       - Manage sub spaces and sub chats with different categories
       - Manage categories (Add/Edit/View/Delete)
- [x] #1958
- [x] #1961

- [x] #2193

- [x] #2207
       - Start DM, New Group, New Space, Explore Space, Report, Support
       - Add Announcements, Add Task List, Add Task Item, Add Pin, Add Event
       - Bookmarked spaces list
       - Bookmarked task list
       - Bookmarked pins list

- [x] Quick search screen refactoring  
       - Quick search for spaces, tasks, events & pins
       - Recently used spaces, tasks, events and pins on start of the screen
       - Quick filters buttons

- [-] Orders management for Pins, Task
       - Manage orders of the pins, task list and task items
       - [x] Manage orders of the categories for spaces and chats

- [x] Make phosphoricons.com as default icon library

- [x] #2127
       - Able to pick any icon from the list
       - Able to pick background color

- [x] #2091
       - Link, Image, Video, File

- [x] https://github.com/acterglobal/a3/issues/2015
       - User should able to add attachments at the time of creating pin
       - General UI-UX improvements

- [ ] Announcements Feature improvements 
       - Share announcements to chat
       - Share announcements to other apps
       - [x] Show read counts
       - [x] Double tap to go to the first announcement

- [ ] Event Feature improvements 
       - [x] Recurring events -> Copy as new
       - [x] Sync events to devices default calendar
       - Event location

- [ ] Task Feature improvements 
       - Task Item assignments
       - [x] Inline changes for due date and assignments
       - Remove collapse and Expanded behaviour

- [ ] Desktop UI-UX improvements

**Comment by gnunicorn** [comment]
We also wanted to switch to https://phosphoricons.com/ , no?

**Comment by kumarpalsinh25** [comment]
> We also wanted to switch to https://phosphoricons.com/ , no?

Oh yes, let me add that point also above the `Icon/Emoji for Pins, Task List and Space Categories` point.

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Most of the point of this tracking issue are either completed or move to separate tracking, so can we close this?
