### ISSUE TITLE
Chat Fixes (Tracking)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#2020]
- [x] https://github.com/acterglobal/a3-meta/issues/466
- [x] https://github.com/acterglobal/a3-meta/issues/528
- [x] https://github.com/acterglobal/a3/issues/1855
- [x] https://github.com/acterglobal/a3-meta/issues/491
- [x] https://github.com/acterglobal/a3-meta/issues/468
- [x] https://github.com/acterglobal/a3-meta/issues/464
- [x] https://github.com/acterglobal/a3-meta/issues/463
- [ ] https://github.com/acterglobal/a3/issues/2102
- [ ] https://github.com/acterglobal/a3-meta/issues/459
- [x] https://github.com/acterglobal/a3-meta/issues/458
- [x] https://github.com/acterglobal/a3/issues/2112
- [x] https://github.com/acterglobal/a3-meta/issues/467
- [x] https://github.com/acterglobal/a3-meta/issues/439
- [x] https://github.com/acterglobal/a3-meta/issues/444
- [x] https://github.com/acterglobal/a3-meta/issues/441
- [x] https://github.com/acterglobal/a3-meta/issues/440
- [x] https://github.com/acterglobal/a3/issues/1988
- [x] https://github.com/acterglobal/a3-meta/issues/412
- [x] https://github.com/acterglobal/a3/issues/2021
- [ ] https://github.com/acterglobal/a3-meta/issues/443
- [x] https://github.com/acterglobal/a3/issues/1663
- [x] https://github.com/acterglobal/a3-meta/issues/261
- [x] https://github.com/acterglobal/a3/issues/1614
- [x] https://github.com/acterglobal/a3-meta/issues/530
- [x] https://github.com/acterglobal/a3-meta/issues/527
- [x] https://github.com/acterglobal/a3-meta/issues/529

Added after 3 October 2024:
- [x] https://github.com/acterglobal/a3-meta/issues/554
- [ ] https://github.com/acterglobal/a3-meta/issues/553
- [ ] https://github.com/acterglobal/a3-meta/issues/552
- [ ] https://github.com/acterglobal/a3-meta/issues/550
- [ ] https://github.com/acterglobal/a3-meta/issues/548
- [ ] https://github.com/acterglobal/a3-meta/issues/540

**Comment by emilvincentz** [comment]
btw. @gtalha07 i have tried to track some of issues related to chat here in case its a help

**Comment by emilvincentz** [comment]
@gtalha07 added a couple of new ones at the top, that would be great to have a fix for (feedback from users)
- "When copying text.."
- "Doesnt make space.."

**Comment by gnunicorn** [comment]
may I recommend _adding_ at the end? that makes it a lot easier for someone to catch up..

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Can we combine this with https://github.com/acterglobal/a3/issues/2137 ?

**Comment by gnunicorn** [comment]
@kumarpalsinh25 I am not sure combining makes sense as the other is more about chat-ng and many of these bugs are structurally fixed in chat-ng ... it's rather a list to check against in the end...
