### ISSUE TITLE
[tracking] Post mentions upgrade fallout

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2024]
We've identified a few problems around the chat text bar since we merged the new mentions feature that need to be dealt with (no particular order):

- [x] #2022
- [x] #2021
- [x] #1989
- [x] #1988
- [x] https://github.com/acterglobal/a3-meta/issues/444
- [x] https://github.com/acterglobal/a3-meta/issues/441
- [x] https://github.com/acterglobal/a3-meta/issues/440
- [x] https://github.com/acterglobal/a3-meta/issues/448
- [x] https://github.com/acterglobal/a3/issues/2040
- [x] https://github.com/acterglobal/a3/issues/2049
- [x] https://github.com/acterglobal/a3-meta/issues/457

**Comment by gtalha07** [comment]
Closing milestone as completed!
