### ISSUE TITLE
[Tracking]  Better Error messages

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2097]
Splitting the open tasks of #2089 into several issues. Putting them here for tracking.

1. [x] For entire pages, a good looking error messages overlaying the loading content, with (where possible) retry-option and bug-reporting -> #2089
  - [x] do something smart about the passed error (e.g. parsing 'not found' and show something less threatening) -> #2089
2. [x] for inline elements -> #2100
   - [x] inline text: show a simplified, less threatening error and open that dialog on click
   - [x] inline boxes: show a simplified, less threatening error and retry-option (and optional dialog opening)
4. [x] submit the routing, error, stacktrace via the bug reporter. #2089

Implemented for:
- [x] SpaceDetails -> #2089
- [x] Pins -> #2089
   - [x] PinsList, with Tests 
   - [x] PinsDetails, with Tests
- [x] Tasks https://github.com/acterglobal/a3/pull/2101
- [x] Events https://github.com/acterglobal/a3/pull/2101
  - [ ] inlined in news-actions, see https://github.com/acterglobal/a3/pull/2096
- [ ] Joining / Accepting Invites
   - [ ] https://github.com/acterglobal/a3-meta/issues/472 -> https://github.com/acterglobal/a3/pull/2096
- [ ] Images in Chat
  - [ ] https://github.com/acterglobal/a3-meta/issues/455 -> https://github.com/acterglobal/a3/pull/2100

Fixes https://github.com/acterglobal/a3/issues/1779

**Comment by gnunicorn** [comment]
considered finished for now.
