### ISSUE TITLE
Deep linking and Sharing

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2223]
We want to be able to share and accept links that open the app and allow direct interactions with them. This is a tracking issue for the several implementation details to be managed for this.

## Internal Linking
 - [ ] sharing links to spaces & chats
 - [ ] properly display/preview spaces & chat links
 - [ ] devise internal objects link scheme / referencing from other rooms
 - [ ] previews scheme for linked objects where no data is available yet
 - [ ] sharing object-links into chat

## Deep linking
 - [ ] open app on matrix-to-links
 - [ ] open app on object links

## External "linking"
 - [ ]  sharing links to external systems with proper previews (e.g. WhatsApp, Slack, Websites)
 - [ ] Preview-Website to share specific info?

## Extra linking
 - [ ] "Persists"-action on chat-messages

**Comment by emilvincentz** [comment]
when clicking on "open in Acter" in browser, it still doesnt open the Acter app @kumarpalsinh25 @gnunicorn

**Comment by emilvincentz** [comment]
Also when i click on the shared link (in a chat on Acter) it opens a browser window, instead of redirecting me in the chat
