### ISSUE TITLE
Engaging Tasks

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2227]
tasks need to be re-worked and become an engaging feature in the app:

- [ ] Be able to invite people to take over a task
- [ ] We need an actual quick action for tasks (with extra fields)
- [ ] redsign inline-adding (it doesn't work right now)
- [ ] easy overview of tasks and their assignment for larger organizations (?) https://github.com/acterglobal/a3/issues/2033

Further bugs that need to be addressed:

- [ ] https://github.com/acterglobal/a3/issues/1877
- [ ] https://github.com/acterglobal/a3/issues/2047
- [ ] https://github.com/acterglobal/a3/issues/1695
- [ ] https://github.com/acterglobal/a3/issues/1669
- [ ] https://github.com/acterglobal/a3/issues/2195
