### ISSUE TITLE
Engaging Update Stream

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2228]
Updates are cool, but we need them to be more engaging. In particular we want:

- [x] #2293
- [x] #2294
- [x] #2363
- [x] push notifications for comments? but at least put them into activity stream 
- [x] Fix the color contrast - https://github.com/acterglobal/a3/issues/1704
- [x] #2525
- [x] #2502
- [x] double tap to jump to first boost
- [x] #2526
      by adding a drop shadow and using full icons (though with a bit of transparency)

can we do these?

- [ ] paginate the entire history
- [ ] sharing boosts to chat -> content sharing?!?
- [ ] sharing boost content to external chat system?

**Comment by emilvincentz** [comment]
can we please also enable text on top of a image slide?

**Comment by kumarpalsinh25** [comment]
Closing this as primary work for Engaging Update is completed.
