### ISSUE TITLE
Spring Cleaning 2024#01

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2402]
- [x] ios back gesture not working, https://github.com/acterglobal/a3/pull/2401
- [x] Fixes AppBar safe area issue https://github.com/acterglobal/a3/pull/2403
- [x] Better way of managing full screen image screen with hide/show app bar with zooming
- [x] https://github.com/acterglobal/a3/pull/2404
- [x] Quick Actions safe area on iOS
- [x] Missing title in Members List Page https://github.com/acterglobal/a3/pull/2407
- [x] #2405
- [ ] #2406
- [x] https://github.com/acterglobal/a3/pull/2408
- [x] https://github.com/acterglobal/a3/pull/2409#pullrequestreview-2481506888

**Comment by gnunicorn** [comment]
closing as we have fixed all or moved them over to specific issues.
