### ISSUE TITLE
Chat Demo tracking

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#303]
We must be able to:
 - [x] Open an existing chat
 - [x] send message in chat
 - [x] see live messages arrive in the chat window
 - [x] emoji-reactions #139 
 - [x] replies #302
 - [x] read-notifications
 - [x] image upload / see images in chat
 - [ ] upload documents / download documents from chat
