### ISSUE TITLE
Tasks-Demo tracking issue

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#315]
Overview tracking issue for the tasks section

- [ ] Minor UI fixes:
 - [x] need bottom tab access point
 - [ ] bottom bar should be visible
- [ ] Disable unimplemented features (like #310 )
   - [ ] plus button
   - [ ] add task button
   - [ ] top filters
   - [ ] notifications bell 
 - [ ] Update content to reflect Demo data (see #311 )

**Comment by gnunicorn** [comment]
> bottom bar should be visible

works correctly from the bottom bar but not with the sidebar at the moment. think this needs fixes of routing.

**Comment by gnunicorn** [comment]
outdated.
