### ISSUE TITLE
Invite to chat facilities [tracking]

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#796]
Currently we can create chats, but then can't invite anyone from the acter UI. This is a tracking issue as we have multiple aspects to take care of/for here. In order of easiness to implement:

- [x] ability to invite users to a chat from within a chat -- should reuse the existing invite-to-space-widgets here, should be fairly straight forward to implement
- [x] list of users of a chat (needs some designs) -- can probably also be analogous to the space-members-widget, too
- [x] change power-levels of users in a chat (as above)
- [ ] during the creation process:
    - [x] asking who should be invited to a space with options to invite everyone from the space this is part of
    - [ ] allowing to configure join-rules (invited, public-for-space, knock, etc)

**Comment by emilvincentz** [comment]
Currently we dont have any empty state for chat.
However we really want to make it as easy as possible for people to onboard others into their spaces/chats, so they can start using Acter.
Concretly for chat, proposing:
1. that we similar to element add an empty state, that display "invite to this chat" button and "share "link button" 
2. Show encryption status text field.
3. Regarding change history/log e.g. "emil join the room, made the room invite only, room history"  we should either display this, or do something else. Right now in Acter it just shows a lot of small empty blobs.
4. Lastly change to display the display names, instead of usernames.



![Image](https://github.com/acterglobal/a3/assets/77483554/1ac50931-d181-4fcf-a3ba-4e9b15092eac)
![Image](https://github.com/acterglobal/a3/assets/77483554/a109608d-b69e-4804-b477-1da1720a16d8)
![Image](https://github.com/acterglobal/a3/assets/77483554/939eb521-89dc-4927-81ef-d574ab64fa80)

**Comment by gnunicorn** [comment]
with kumars latest changes, this is good for now!
