### ISSUE TITLE
Improve chat

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#862]
more or less in prioritisted order.

- [x] [Edit message](https://github.com/acterglobal/a3/issues/888)
- [x] #1066
- [x] #1067
- [x] #1074 
- [x] [Gallery not being accessed while uploading image in chat room](https://github.com/acterglobal/a3/issues/861)
- [x] #1115
- [x] Emojii reaction indicator (right now you can not see the person/people who reacted with emoji)
- [x] Change default emoji reaction to (❤️👍 🙏 😂 🙌 😮)
- [ ] [Invite to chat facilities [tracking]](https://github.com/acterglobal/a3/issues/796)
- [ ] [Activity indicator on chat overview page](https://github.com/orgs/acterglobal/projects/3/views/4?filterQuery=status%3A%22Recently+Done%22%2C%22In+progress%22%2CBacklog%2CNext%2C%22Ready+for+Review%22++activity&pane=issue&itemId=35458171)
- [ ] [Reactivate messages receipt](https://github.com/acterglobal/a3/issues/812)
 - [x] Notable delay when pressing enter or send (somtimes up to 2seconds). This has led me to clicking twice, which send the. messge twice. #952 
 - [x] #1068
 - [x] #1069

Nice to:
- [x] safe chat draft. (when i start writing in one chat and switch to view another chat without sending it, the draft is gone when going back to the chat.
- [x] React with emoji, by clicking the emoji already submitted to a message/file/image

When final designs has been reviewed and approved, we need to implement:
[Implement create chat flow](https://github.com/acterglobal/a3/issues/853)

**Comment by gnunicorn** [comment]
Chat Creation flow: https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=6188-65861&mode=design
