### ISSUE TITLE
Issues after latest nightly (29.08.23)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#891]
- [x] Emoji reaction view is showing users who reacted, but not the emojiis -> #900
- [x] emojis given, are not showing in chat. Also emojii snippet is not showing emojiis -> #900
- [x] When entering chat on IOS, there is no text input field -> #902 
- [x] chat sidebar is also showing on ios (should not show)  -> #902 
- [x] Pins seems to require description when link already inserted (should not be required) -> #904
- [x] Pins. Error in the link field. Although i already inserted link, it says: "Text or URL must be given". -> #904 
- [x] Chat room route push bug .i.e. navigating to another room while current route is room id will throw exceptions and keeps the room view blocked. -> #915

**Comment by emilvincentz** [comment]
![Image](https://user-images.githubusercontent.com/77483554/264016990-c8ec9bb2-4e6a-4f47-a49e-f4f4f4a95daa.png)
![Image](https://user-images.githubusercontent.com/77483554/264016988-a0b22a34-b980-4128-9272-5012995f1457.png)
![Image](https://user-images.githubusercontent.com/77483554/264016989-a225ec82-12ff-4038-8891-64cf820b11b5.PNG)
![Image](https://user-images.githubusercontent.com/77483554/264016991-0c9860fa-d7b9-4635-8e0f-050b83e2a0ca.PNG)
![Image](https://user-images.githubusercontent.com/77483554/264016992-bfd0dd8d-85c2-48ab-89fa-ac98ff9c6a0e.png)
![Image](https://user-images.githubusercontent.com/77483554/264016993-723c279a-5d1f-428d-83fd-db63acf96cb2.png)
![Image](https://user-images.githubusercontent.com/77483554/264016994-efd9ab2e-5b2e-44d1-b32a-ef2fe26df06f.png)
