### ISSUE TITLE
[tracking] Reporting and blocking of content and users

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#909]
As an app that shows user generated content to people, we need to add the ability to report content, block users and remove content from a users feed easily and quickly.

At this point, there already exist two UI's that _indicate_ to provide such a feature:

the `...` on an News Item:
![news-item-report](https://github.com/acterglobal/a3/assets/40496/7d65b6d2-bb93-4128-8231-5478b08f199f)

and a long-press on a chat message:

![chat-message-report](https://github.com/acterglobal/a3/assets/40496/1362225f-5839-4461-9b4c-a3bac78a3efd)

What we need:

- [x] implement the [`MemberProfile.ignore`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/room/struct.RoomMember.html#method.ignore) on the rust SDK
- [x] implement [the `report_content` API](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_base/ruma/api/client/room/report_content/index.html) on the rust SDK
- [x] Create a singular [report-content flow](https://github.com/acterglobal/a3/issues/913) (based on the UI of the news item)
- [x] hook that up to:
    - [x] News
    - [x] Pins
    - [x] Events
    - [x] Chat Room Message 
- [x] Add the ability to ignore a User from the chat screen as well as the space-members screen, #927

**Comment by bitfriend** [comment]
Implemented [blocking of user and content](https://github.com/acterglobal/a3/pull/912)

**Comment by gnunicorn** [comment]
fixed by #927
